GET http://localhost:8080/member/member/count
Accept: application/json
token:123

###
POST http://localhost:8080/member/member/sendCode
Content-Type: application/json

{

"mobile" : "11335566776"

}
###
POST http://localhost:8080/member/member/login
Content-Type: application/json

{

"mobile" : "11335566776",
  "code" : "8888"
}
> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.content.token));
    client.global.set("token", response.body.content.token);
%}