server:
  servlet:
    context-path: /business
  port:
    8002
logging:
  level:
    com:
      example:
        train:
          member:
            mapper: trace
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: train_business
    password: Business12306
    url: jdbc:mysql://rm-cn-x0r3cesys000itvo.rwlb.rds.aliyuncs.com/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
